### ISSUE TITLE
Traceback on creating new Parent Profile.

### ISSUE THREAD

**Issue by poonam-serpentcs** [ForamSerpentCS/OdooEduERP#14]
Create and Save Parent Profile.

```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/home/serpentcs/WorkSpace/14.0/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/home/serpentcs/WorkSpace/14.0/odoo/http.py", line 682, in dispatch
    result = self._call_function(**self.params)
  File "/home/serpentcs/WorkSpace/14.0/odoo/http.py", line 358, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/serpentcs/WorkSpace/14.0/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/serpentcs/WorkSpace/14.0/odoo/http.py", line 346, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/serpentcs/WorkSpace/14.0/odoo/http.py", line 911, in __call__
    return self.method(*args, **kw)
  File "/home/serpentcs/WorkSpace/14.0/odoo/http.py", line 530, in response_wrap
    response = f(*args, **kw)
  File "/home/serpentcs/WorkSpace/14.0/addons/web/controllers/main.py", line 1359, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/serpentcs/WorkSpace/14.0/addons/web/controllers/main.py", line 1351, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/serpentcs/WorkSpace/14.0/odoo/api.py", line 394, in call_kw
    result = _call_kw_model_create(method, model, args, kwargs)
  File "/home/serpentcs/WorkSpace/14.0/odoo/api.py", line 374, in _call_kw_model_create
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-189>", line 2, in create
  File "/home/serpentcs/WorkSpace/14.0/odoo/api.py", line 323, in _model_create_single
    return create(self, arg)
  File "/home/serpentcs/WorkSpace/wfh_projects/OdooEduERP/school/models/parent.py", line 74, in create
    self.env['res.users'].create(user_vals)
  File "<decorator-gen-190>", line 2, in create
  File "/home/serpentcs/WorkSpace/14.0/odoo/api.py", line 323, in _model_create_single
    return create(self, arg)
  File "/home/serpentcs/WorkSpace/wfh_projects/OdooEduERP/school/models/res_users.py", line 14, in create
    user_rec = super(ResUsers, self).create(vals)
  File "<decorator-gen-161>", line 2, in create
  File "/home/serpentcs/WorkSpace/14.0/odoo/api.py", line 344, in _model_create_multi
    return create(self, [arg])
  File "/home/serpentcs/WorkSpace/14.0/addons/digest/models/res_users.py", line 12, in create
    users = super(ResUsers, self).create(vals_list)
  File "<decorator-gen-137>", line 2, in create
  File "/home/serpentcs/WorkSpace/14.0/odoo/api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "/home/serpentcs/WorkSpace/14.0/addons/auth_signup/models/res_users.py", line 246, in create
    users_with_email.with_context(create_user=True).action_reset_password()
  File "/home/serpentcs/WorkSpace/14.0/addons/auth_signup/models/res_users.py", line 205, in action_reset_password
    template.send_mail(user.id, force_send=force_send, raise_exception=True)
  File "/home/serpentcs/WorkSpace/14.0/addons/mail/models/mail_template.py", line 248, in send_mail
    values['recipient_ids'] = [(4, pid) for pid in values.get('partner_ids', list())]
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/serpentcs/WorkSpace/14.0/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/serpentcs/WorkSpace/14.0/odoo/http.py", line 314, in _handle_exception
    raise exception.with_traceback(None) from new_cause
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by poonam-serpentcs** [comment]
Still getting Same Issue.
