### ISSUE TITLE
Terminated student is not displayed in Alumni/Terminate.

### ISSUE THREAD

**Issue by poonam-serpentcs** [ForamSerpentCS/OdooEduERP#17]
Create Student --> Done --> Terminate

https://prnt.sc/vxf96l

Go to Alumni/Terminate Menu 
https://prnt.sc/vxf9ok

It is empty

**Comment by poonam-serpentcs** [comment]
Getting Traceback on Terminating Student 

![Screenshot (3)](https://user-images.githubusercontent.com/51950448/111584750-467fb580-87e4-11eb-823b-700f19809150.png)


```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/home/serpentcs/WorkSpace/14.0/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/home/serpentcs/WorkSpace/14.0/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/home/serpentcs/WorkSpace/14.0/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/serpentcs/WorkSpace/14.0/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/serpentcs/WorkSpace/14.0/odoo/http.py", line 347, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/serpentcs/WorkSpace/14.0/odoo/http.py", line 912, in __call__
    return self.method(*args, **kw)
  File "/home/serpentcs/WorkSpace/14.0/odoo/http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "/home/serpentcs/WorkSpace/14.0/addons/web/controllers/main.py", line 1381, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/home/serpentcs/WorkSpace/14.0/addons/web/controllers/main.py", line 1369, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/serpentcs/WorkSpace/14.0/odoo/api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/serpentcs/WorkSpace/14.0/odoo/api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/serpentcs/WorkSpace/wfh_projects/OdooEduERP/school/wizard/teriminate_reason.py", line 29, in save_terminate
    rec.active = False
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/serpentcs/WorkSpace/14.0/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/serpentcs/WorkSpace/14.0/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
AttributeError: 'student.reminder' object has no attribute 'active'
```
